spring:
  config:
    import: "configserver:"
  application:
    name: eureka-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:docker}
  cloud:
    config:
      uri: http://${CONFIG_HOST:configserver}:${CONFIG_PORT:7071}