spring:
  application:
    name: chat-api-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7070/realms/spmia-realm
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: ostock
            client-secret: 0VFvtUzzrORmAVqcgykHSzwiaKc5615O
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:7070/realms/spmia-realm

server:
  port: 8180

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

jwt:
  auth:
    converter:
      resource-id: ostock
      principal-attribute: preferred_username