spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3307/chatdb
    username: guest
    password: guest
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none

  application:
    name: chat-api-service

server:
  port: 8180

eureka:
  client:
    enabled: false

management:
  tracing:
    enabled: false

jwt:
  auth:
    converter:
      resource-id: ostock
      principal-attribute: preferred_username