CHAT_NODE_ID: ${CHAT_NODE_ID} # 컨테이너/vm마다 고유값 주입
ONLINE_KEY_PREFIX: 'socket:online:1:'
OUTBOX_KAFKA_TOPIC: 'cdc.chatdb.outbox'
OUTBOX_GROUP_ID: 'chat-outbox-consumers'
PUSH_NOTIFICATION_TOPIC: 'push-notification-topic'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/chatdb
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST} # redis_container
      port: ${REDIS_PORT}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

  # Kafka ?? ??
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: chat-messages-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.nicehcy.chatservice.dto
        spring.json.value.default.type: com.nicehcy.chatservice.dto.MessageDto

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT:8070}/eureka/

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: W3C
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT:9411}/api/v2/spans

jwt:
  secret: ${JWT_SECRET}

server:
  port: 8080