spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/chatdb
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST} # redis
      port: ${REDIS_PORT} # 6379

server:
  port: 8030

jwt:
  accesstoken-expiration-time: 60 # 초 단위
  overlap-window: PT30S           # RT 회전 후 이전 RT 허용 창
  refresh-ttl: P1D                # Refresh Token 만료 기간
  secret: ${JWT_SECRET}

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka # http://eurekaserver:8070/eureka