spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/chatdb
    username: guest
    password: guest
  jpa:
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: redis # redis
      port: 6379 # 6379

server:
  port: 8030

jwt:
  accesstoken-expiration-time: 60 # 초 단위
  overlap-window: PT30S           # RT 회전 후 이전 RT 허용 창
  refresh-ttl: P1D                # Refresh Token 만료 기간
  secret: "Y69LhQRsm/zGEMqQTNuyeeXFdrqqfPpIAnXmZttuLsg="

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka # http://eurekaserver:8070/eureka