PUSH_NOTIFICATION_TOPIC: 'push-notification-topic'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/chatdb
    username: guest
    password: guest
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: Kafka00Service:9092,Kafka01Service:9092,Kafka02Service:9092
    consumer:
      group-id: push-notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*" # TODO
        spring.json.value.default.type: com.nicehcy2.pushnotificationservice.dto.PushNotificationRequestDto
  application:
    name: pushnotificationservice

server:
  port: 8090