PUSH_NOTIFICATION_TOPIC: 'push-notification-topic'

spring:
  application:
    name: pushnotificationservice

kafka:
  bootstrap-servers: localhost:10000,localhost:10001,localhost:10002
  consumer:
    group-id: push-notification-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: com.nicehcy2.pushnotificationservice.dto
      spring.json.value.default.type: com.nicehcy2.pushnotificationservice.dto.PushNotificationRequestDto
